global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'registrar'
    static_configs:
      - targets: ['registrar-api-1:7001']
  - job_name: 'sequencer'  
    static_configs:
      - targets: ['sequencer-1:8001']
  - job_name: 'merkle-batcher'
    static_configs:
      - targets: ['merkle-batcher-1:9001']
